name: Hello World CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version 18
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - run: npm install
      - run: npx tsc index.ts
